#
# This workflow is run regularly and tests the official package distribution,
# then uploads status reports, by calling the test-all update-latest-report
# YML workflows.
#
# It is also run when the package definitions in the `main` branch are
# updated.
#
name: "Test all and report status"

on:
  workflow_dispatch: # for debugging
  push:
    paths:
      - 'packages/*/meta.json'
    branches:
      - main
  schedule:
    - cron:  '00 2 * * *'

# only run at most one instances of this workflow at a time for each branch
# resp. tag. Starting a new one cancels previously running ones.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # master
  test-all-master:
    name: "master"
    uses: ./.github/workflows/test-all.yml
    with:
      which-gap: master

  update-latest-master:
    name: "Upload master report"
    needs: test-all-master
    if: always()
    uses: ./.github/workflows/update-latest-report.yml
    with:
      which-gap: master

  # 4.11.1
  test-all-4-11-1:
      name: "4.11.1"
      uses: ./.github/workflows/test-all.yml
      with:
        which-gap: 4.11.1

  update-latest-4-11:
    name: "Upload 4.11.1 report"
    needs: test-all-4-11-1
    if: always()
    uses: ./.github/workflows/update-latest-report.yml
    with:
      which-gap: 4.11.1
