name: Run tests

on: workflow_dispatch  # for debugging

jobs:
  py39: 
    name: "Run tests in Python 3.9"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest mock
          
      - name: Run tests
        run: pytest tools/tests/test*.py -vv
